services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: marsh
      POSTGRES_PASSWORD: marsh
      POSTGRES_DB: marsh
    ports:
      - "5432:5432"
    volumes:
      - marsh_pgdata:/var/lib/postgresql/data

volumes:
  marsh_pgdata:
